# Generated by Django 3.0 on 2019-12-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=2000)),
                ('picture', models.CharField(max_length=1000)),
            ],
        ),
    ]
